info:
  name: get_visitor_application
  type: http
  seq: 4
  tags:
    - users

http:
  method: GET
  url: "{{baseUrl}}/api/v1/user/visitor-application"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Current visitor application or null
    request:
      url: "{{baseUrl}}/api/v1/user/visitor-application"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          null
  - name: 401 Response
    description: Not authenticated
    request:
      url: "{{baseUrl}}/api/v1/user/visitor-application"
      method: GET
    response:
      status: 401
      statusText: Unauthorized
      body:
        type: text
        data: ""
